platform :ios, '12.0'

target 'UseDesk_Example' do
  use_frameworks!
  
  pod 'UseDesk_SDK_Swift', :path => '../'

  target 'UseDesk_Tests' do
    inherit! :search_paths
  end
end
install! 'cocoapods', :disable_input_output_paths => true
