platform :ios, '14.0'

target 'UseDesk_Example' do
  use_frameworks!
  
  pod 'UseDesk_SDK_Swift', :path => '../'
  pod 'IQKeyboardManagerSwift'
  
  target 'UseDesk_Tests' do
    inherit! :search_paths
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
  
end

